export enum MicrosoftTenantStatus {
  PENDING_CONSENT = 'PENDING_CONSENT',
  ACTIVE = 'ACTIVE',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  CERTIFICATE_EXPIRED = 'CERTIFICATE_EXPIRED',
  DISABLED = 'DISABLED',
}
