name: Library Checks

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-
      - name: Install modules
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Cache workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}
      - name: create env file
        env:
          DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
        run: echo "$DEV_ENV_FILE" > .env
      - name: ESLint changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          ignore_patterns: "samples/**"
          config_path: "eslint.config.mjs"
          extra_args: "--max-warnings=0"
