name: Sample App Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test-sample-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies for library
      run: npm ci
      
    - name: Build library
      run: npm run build
      
    - name: Install yalc globally
      run: npm install -g yalc
      
    - name: Publish library to yalc
      run: yalc publish
      
    - name: Setup sample app
      run: |
        cd samples/nestjs-outlook-example
        npm ci
        yalc add @checkfirst/nestjs-outlook
        npm install
        
    - name: Build sample app
      run: |
        cd samples/nestjs-outlook-example
        npm run build
    - name: Cache workspace
      uses: actions/cache@v3
      with:
        path: .
        key: workspace-${{ github.sha }}

    - name: Test sample app
      run: |
        cd samples/nestjs-outlook-example
        npm test -- --passWithNoTests
  lint:
    needs: test-sample-app
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: .
          key: workspace-${{ github.sha }}
      - name: create env file
        env:
          DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
        run: echo "$DEV_ENV_FILE" > .env
      - name: ESLint changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          path: "samples/nestjs-outlook-example"
          config_path: "eslint.config.mjs"
          extra_args: "--max-warnings=0"
