name: Test Sample App with Library Changes

on:
  pull_request:
    branches: [ main ]

jobs:
  test-sample-app:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies for library
      run: npm ci
      
    - name: Build library
      run: npm run build
      
    - name: Install yalc globally
      run: npm install -g yalc
      
    - name: Publish library to yalc
      run: yalc publish
      
    - name: Setup sample app
      run: |
        cd samples/nestjs-outlook-example
        npm ci
        yalc add @checkfirst/nestjs-outlook
        npm install
        
    - name: Build sample app
      run: |
        cd samples/nestjs-outlook-example
        npm run build
        
    - name: Test sample app
      run: |
        cd samples/nestjs-outlook-example
        npm test -- --passWithNoTests 