name: Update README TOC

on:
  pull_request:
    paths:
      - 'README.md'
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "## Table of Contents"
          MAX_HEADER_LEVEL: 3
          FOLDING: false
          COMMIT_MESSAGE: "docs: update README table of contents"
          TARGET_PATHS: "README.md"
          CREATE_PR: false
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com" 